package main

import "./utils"

// syncBaseClass is the scoped CSS class generated by cssClass() via syncStatusStyles().
// Set once in createAppShell(), used in the syncClass computed in setupReactiveDOM.
var syncBaseClass string

// ── HTML builders (SafeHTML via trusted()) ────────────────────

func renderTodoHTML(t Todo) SafeHTML {
    cls := "todo-item"
    if t.done {
        cls = "todo-item done"
    } else if t.isUrgent() {
        cls = "todo-item high"
    }

    checked := ""
    if t.done {
        checked = " checked"
    }

    badge := ""
    if t.isUrgent() {
        badge = `<span class="badge">urgent</span>`
    }

    id := String(t.id)
    return trusted(
        `<li class="` + cls + `" draggable="true" data-id="` + id + `">
<input type="checkbox" class="todo-cb" data-action="toggle" data-todo-id="` + id + `"` + checked + ` />
<span class="todo-text">` + html.EscapeString(t.text) + `</span>` +
        badge +
        `<button class="del-btn" data-action="delete" data-todo-id="` + id + `">✕</button>
</li>`,
    )
}

func renderFilterBarHTML(activeFilter int) SafeHTML {
    filters := [...]int{FilterAll, FilterActive, FilterCompleted}
    var b strings.Builder
    b.WriteString(`<div class="filter-bar">`)
    for _, f := range filters {
        cls := "filter-btn"
        if f == activeFilter {
            cls = "filter-btn active"
        }
        b.WriteString(`<button class="` + cls + `" data-action="filter" data-filter="` + String(f) + `">`)
        b.WriteString(filterLabel(f))
        b.WriteString(`</button>`)
    }
    b.WriteString(`</div>`)
    return trusted(b.String())
}

// ── App shell ─────────────────────────────────────────────────

// createAppShell builds the full app as a Reactive.Component and mounts it
// into #app. Using the Component lifecycle eliminates all querySelector /
// getElementById calls from application code:
//
//   state()    — all signals the template's data-* attributes need; _proc
//                passes existing Signal objects through unchanged (v?.get check).
//   template() — full HTML with data-ref on every key element plus all the
//                reactive scan attributes (data-model, data-on-*, data-class-*,
//                data-attr-*, data-bool-*, data-visible, data-if, data-text).
//   mount()    — called after render()+scan(); comp.refs.* is populated.
//                Applies per-section cssClass() to refs, builds AppElements,
//                then wires setupReactiveDOM and setupDragDrop — no DOM queries.
func createAppShell(inputValue Signal) {
    comp := createReactiveComponent()

    // els is populated in mount() below; closures over it (onAdd, onKeydown)
    // are only invoked after mount() has run, so the value is always set.
    var els AppElements

    // Derived signals created here so they can be referenced inside state().
    hasError := Signals.computed(func() any {
        return errorSignal.get() != ""
    }, "hasError")
    placeholder := Signals.computed(func() any {
        if highPriority.get() {
            return "What's urgent? (high priority)"
        }
        return "What needs to be done?"
    }, "placeholder")

    // state() — Component._proc passes any value with .get through unchanged.
    // Functions would be converted to computed signals by _proc, so event
    // handlers are assigned directly to the component object below instead.
    comp.state = func() any {
        return map[string]any{
            "inputValue":       inputValue,
            "hasError":         hasError,
            "errorMsg":         errorSignal,
            "isHighPriority":   highPriority,
            "showPriorityHint": highPriority,
            "placeholder":      placeholder,
            "isSaving":         savingSignal,
        }
    }

    // Event handlers assigned directly so scan's data-on-* resolver finds them
    // as plain functions rather than computed signals.
    comp.onAdd = func(e any) any {
        submitInput(els.input, inputValue)
        return nil
    }
    comp.onKeydown = func(e any) any {
        if e.key == "Enter" {
            submitInput(els.input, inputValue)
        }
        return nil
    }
    comp.onPriority = func(e any) any {
        togglePriorityMode()
        return nil
    }

    // template() — every key element carries data-ref so comp.refs is
    // populated by scan() without any querySelector calls. All reactive scan
    // attributes are declared inline here; they are resolved from comp (this)
    // which holds the signals set up in state() and the handlers above.
    comp.template = func() any {
        return trusted(`<div class="card" data-ref="card">
  <header class="header" data-ref="header">
    <div class="header-top">
      <div class="header-icon">✓</div>
      <h1>Todos Reactive</h1>
      <span class="high-badge" data-ref="badge"></span>
      <span class="sync-status" data-ref="syncStatus"></span>
    </div>
    <p class="tagline">Built with <a href="https://github.com/seriva/gofront" target="_blank"><strong>GoFront</strong></a> — Go compiled to JS</p>
  </header>
  <div class="input-row" data-ref="inputRow">
    <input class="todo-input" type="text" autocomplete="off"
           data-ref="input"
           data-model="inputValue"    data-on-keydown="onKeydown"
           data-class-high="isHighPriority"
           data-attr-placeholder="placeholder"
           data-bool-disabled="isSaving" />
    <button type="button" class="priority-btn" data-ref="priorityBtn" data-on-click="onPriority">⚡ Normal</button>
    <button type="button" class="add-btn"      data-ref="addBtn"      data-on-click="onAdd">Add</button>
    <span class="priority-hint" data-visible="showPriorityHint">⚡ High priority — task will be marked urgent</span>
    <span class="error-msg"     data-if="hasError" data-text="errorMsg"></span>
  </div>
  <div class="list-divider"></div>
  <ul class="todo-list" data-ref="list"></ul>
  <footer class="footer" data-ref="footer">
    <span class="count"       data-ref="countSpan"></span>
    <div  class="filter-area" data-ref="filterArea"></div>
  </footer>
  <div id="stats-bar"></div>
</div>`)
    }

    // mount() — comp.refs.* is fully populated when this runs.
    // Per-section cssClass() is applied to refs instead of querySelector,
    // then AppElements is assembled from refs for the downstream setup functions.
    comp.mount = func() {
        comp.refs.card.classList.add(cardStyles())
        comp.refs.header.classList.add(headerStyles())
        comp.refs.inputRow.classList.add(inputRowStyles())
        comp.refs.list.classList.add(listStyles())
        comp.refs.footer.classList.add(footerStyles())
        syncBaseClass = syncStatusStyles()
        comp.refs.syncStatus.classList.add(syncBaseClass)

        els = AppElements{
            input:       comp.refs.input,
            addBtn:      comp.refs.addBtn,
            priorityBtn: comp.refs.priorityBtn,
            list:        comp.refs.list,
            footer:      comp.refs.footer,
            badge:       comp.refs.badge,
            syncStatus:  comp.refs.syncStatus,
            inputRow:    comp.refs.inputRow,
            countSpan:   comp.refs.countSpan,
            filterArea:  comp.refs.filterArea,
        }
        setupReactiveDOM(els)
        setupDragDrop(els)
    }

    // mountTo clears #app, renders template(), collects refs via scan(),
    // applies styles(), then calls mount() — all without querySelector.
    comp.mountTo("app")
}

// ── Reactive DOM wiring ───────────────────────────────────────

// setupReactiveDOM wires signals → DOM using the full Reactive bind* API.
// Every bind variant from the library is used here with a clear motivation.
func setupReactiveDOM(els AppElements) {
    ctx := Reactive.createComponent()

    // ── List: ctx.bind ────────────────────────────────────────
    listView := ctx.computed(func() any {
        visible := visibleSignal.get()
        if len(visible) == 0 {
            return trusted(`<li class="empty">Nothing here.</li>`)
        }
        items := []SafeHTML{}
        for i := range len(visible) {
            items = append(items, renderTodoHTML(visible[i]))
        }
        return join(items, "")
    }, "listView")
    ctx.bind(els.list, listView, func(v any) any { return v })

    // ── Filter area: ctx.bind (filter buttons + clear-completed) ──
    filterView := ctx.computed(func() any {
        f := filterSignal.get()
        s := statsSignal.get()
        clearBtn := ""
        if s.completed > 0 {
            clearBtn = `<button class="clear-btn" data-action="clear-completed">Clear (` +
                String(s.completed) + `)</button>`
        }
        return trusted(renderFilterBarHTML(f).content + clearBtn)
    }, "filterView")
    ctx.bind(els.filterArea, filterView, func(v any) any { return v })

    // ── Footer visibility: ctx.bindStyle ─────────────────────
    // hide the footer entirely when there are no todos
    ctx.bindStyle(els.footer, "display", ctx.computed(func() any {
        if len(todosSignal.get()) == 0 {
            return "none"
        }
        return ""
    }, "footerDisplay"))

    // ── Count span: ctx.bindMultiple ──────────────────────────
    // Combines two signals (todos + stats) into a single DOM update.
    ctx.bindMultiple(els.countSpan, []any{todosSignal, statsSignal}, func(vals any) any {
        if len(vals[0]) == 0 {
            return ""
        }
        s := vals[1]
        return utils.Plural(s.remaining, "task") + " left"
    })

    // ── Badge: ctx.bindText + ctx.bindStyle ───────────────────
    // bindText — set textContent without innerHTML (no HTML in badge text)
    ctx.bindText(els.badge, ctx.computed(func() any {
        hc := highCountSignal.get()
        if hc > 0 {
            return String(hc) + " urgent"
        }
        return ""
    }, "badgeText"))
    // bindStyle — toggle inline display style reactively
    ctx.bindStyle(els.badge, "display", ctx.computed(func() any {
        if highCountSignal.get() > 0 {
            return "inline-block"
        }
        return "none"
    }, "badgeDisplay"))

    // ── Priority button: ctx.bindClass + ctx.bindText ─────────
    // bindClass — toggle the "on" CSS class based on highPriority signal
    ctx.bindClass(els.priorityBtn, "on", highPriority)
    // bindText — update button label reactively (no innerHTML needed)
    ctx.bindText(els.priorityBtn, ctx.computed(func() any {
        if highPriority.get() {
            return "⚡ High"
        }
        return "⚡ Normal"
    }, "priorityLabel"))

    // ── Add button: ctx.bindBoolAttr + ctx.bindStyle + ctx.bindAttr ──
    // bindBoolAttr — add/remove the "disabled" attribute while a save is running
    ctx.bindBoolAttr(els.addBtn, "disabled", savingSignal)
    // bindStyle — switch background gradient to red when adding urgent todos
    ctx.bindStyle(els.addBtn, "background", ctx.computed(func() any {
        if highPriority.get() {
            return "linear-gradient(135deg, #dc2626, #f87171)"
        }
        return "linear-gradient(135deg, #7c3aed, #a78bfa)"
    }, "addBtnBg"))
    // bindAttr — keep aria-label in sync with the current priority mode
    ctx.bindAttr(els.addBtn, "aria-label", ctx.computed(func() any {
        if highPriority.get() {
            return "Add urgent todo"
        }
        return "Add todo"
    }, "ariaLabel"))

    // ── Sync status: ctx.bindText + ctx.bindAttr ──────────────
    // bindText — update the status message text node directly
    ctx.bindText(els.syncStatus, syncMsgSignal)
    // bindAttr — build the full class string so saving/saved/error styles apply
    ctx.bindAttr(els.syncStatus, "class", ctx.computed(func() any {
        cls := syncClsSignal.get()
        if cls != "" {
            return syncBaseClass + " " + cls
        }
        return syncBaseClass
    }, "syncClass"))

    // ── Event delegation ──────────────────────────────────────
    els.list.addEventListener("change", func(e any) {
        action := e.target.getAttribute("data-action")
        if action == "toggle" {
            idStr := e.target.getAttribute("data-todo-id")
            toggleTodo(int(idStr))
            triggerSave()
        }
    })

    els.list.addEventListener("click", func(e any) {
        action := e.target.getAttribute("data-action")
        if action == "delete" {
            idStr := e.target.getAttribute("data-todo-id")
            removeTodo(int(idStr))
            triggerSave()
        }
    })

    els.filterArea.addEventListener("click", func(e any) {
        action := e.target.getAttribute("data-action")
        switch action {
        case "filter":
            f := int(e.target.getAttribute("data-filter"))
            setFilter(f)
        case "clear-completed":
            clearCompleted()
            triggerSave()
        }
    })

    // ── Reactive.Component used from GoFront ──────────────────
    // createReactiveComponent() returns a bare Reactive.Component instance (any).
    // Because GoFront can assign functions to any-typed properties, we wire
    // template(), styles(), and a computed signal directly onto the object.
    // Component.render() → this.scan(el) will then bind data-text="todoCount"
    // to the signal reactively — no JS subclassing required.
    setupStatsBar()
}

// ── Drag-and-drop via Reactive.Component ──────────────────────

// setupDragDrop uses Reactive.Component (the class-based component context)
// rather than the plain createComponent() context. The key extras it adds:
//   • comp.signal()  — local reactive state scoped to this component
//   • comp.on()      — addEventListener + Signals.batch + auto-cleanup tracking
//   • comp.effect()  — a side effect that re-runs when dependencies change
func setupDragDrop(els AppElements) {
    comp := createReactiveComponent()

    // signal() — create local drag-source state owned by this component
    dragSrcSig := comp.signal(0, "dragSrc")

    // effect() — reactive side effect: keep the browser tab title in sync with
    // the urgent-task count. Re-runs automatically whenever highCountSignal changes.
    comp.effect(func() {
        hc := highCountSignal.get()
        if hc > 0 {
            document.title = fmt.Sprintf("(%d urgent) GoFront Todos", hc)
        } else {
            document.title = "GoFront Todos"
        }
    })

    // on() — wraps handlers in Signals.batch and registers cleanup automatically
    comp.on(els.list, "dragstart", func(e any) {
        li := e.target.closest("li")
        if li == nil {
            return
        }
        dragSrcSig.set(int(li.getAttribute("data-id")))
        li.classList.add("dragging")
        e.dataTransfer.effectAllowed = "move"
    }, nil)

    comp.on(els.list, "dragover", func(e any) {
        li := e.target.closest("li")
        if li == nil {
            return
        }
        // peek() — read the drag-source id without creating a reactive dependency
        targetId := int(li.getAttribute("data-id"))
        if dragSrcSig.peek() != targetId {
            e.preventDefault()
            li.classList.add("drag-over")
        }
    }, nil)

    comp.on(els.list, "dragleave", func(e any) {
        li := e.target.closest("li")
        if li == nil {
            return
        }
        if !li.contains(e.relatedTarget) {
            li.classList.remove("drag-over")
        }
    }, nil)

    comp.on(els.list, "drop", func(e any) {
        e.preventDefault()
        li := e.target.closest("li")
        if li == nil {
            return
        }
        targetId := int(li.getAttribute("data-id"))
        // peek() — read without tracking; we only need the current value once
        src := dragSrcSig.peek()
        if src != targetId {
            moveTodo(src, targetId)
            triggerSave()
        }
    }, nil)

    comp.on(els.list, "dragend", func(e any) {
        li := e.target.closest("li")
        if li != nil {
            li.classList.remove("dragging")
        }
    }, nil)
}

// ── Reactive.Component wired from GoFront ─────────────────────

// setupStatsBar creates a Reactive.Component instance entirely from GoFront,
// exercising the full Component lifecycle:
//
//   state()    — functions become computed signals automatically (via _proc).
//                No manual Signals.computed() call needed.
//   template() — returns SafeHTML; data-text="todoCount" binds the signal;
//                data-ref="counter" is captured into comp.refs.counter by scan().
//   styles()   — scoped cssClass() with hover effects on the counter span.
//   mount()    — called after render() + scan(); refs are populated here so we
//                can attach a click handler via comp.on() with auto-cleanup.
func setupStatsBar() {
    comp := createReactiveComponent()

    // state() — any function value is turned into a ctx.computed() signal by
    // Component._proc(), so initState() creates this.todoCount automatically.
    // The computed returns a SafeHTML value via htmlTag so scan's data-html
    // binding renders it as innerHTML (not escaped text).
    // htmlTag(strings, values...) is the html tagged-template called as a plain
    // function: interpolated values are auto-escaped by the reactive library.
    comp.state = func() any {
        return map[string]any{
            "todoCount": func() any {
                n := len(todosSignal.get())
                return htmlTag([]string{"<strong>", "</strong> in session"}, utils.Plural(n, "todo"))
            },
        }
    }

    // template() — data-html="todoCount" (not data-text) because todoCount is
    // a SafeHTML signal; scan sets innerHTML so the <strong> tag is rendered.
    // data-ref="counter" lets scan() populate comp.refs.counter so mount() can
    // attach events without a querySelector.
    comp.template = func() any {
        return trusted(`<div><span data-ref="counter" data-html="todoCount" title="Show active todos"></span></div>`)
    }

    // styles() — scoped cssClass with an interactive hover on the counter span.
    comp.styles = func() any {
        return cssClass(`
            text-align: center;
            font-size: .65rem;
            color: var(--muted);
            padding: 6px 20px 14px;
            letter-spacing: .04em;
            opacity: .5;
            border-top: 1px solid rgba(255,255,255,.04);
            & span { cursor: pointer; transition: color .15s, opacity .15s; }
            & span:hover { color: var(--accent); opacity: 1; }
            & strong { font-weight: 600; color: var(--text-2); }
        `)
    }

    // mount() — lifecycle hook called after render()+scan(); comp.refs.counter is
    // available here. comp.on() wraps the handler in Signals.batch and registers
    // cleanup automatically — clicking the counter jumps to the Active filter.
    comp.mount = func() {
        comp.on(comp.refs.counter, "click", func(e any) {
            setFilter(FilterActive)
        }, nil)
    }

    // appendTo() runs: initState() → render() (template+styles+scan) → mount()
    comp.appendTo("stats-bar")
}
